name: Self-Hosted Runner Workflow

on:
  push:
    branches:
      - main  # Adjust based on your default branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # This tells GitHub to use your self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Start application
        run: npm start
